switched to Tomorrow-Night colorscheme and lot of improvements

diff --git a/bin/governor b/bin/governor
--- a/bin/governor
+++ b/bin/governor
@@ -1,69 +1,61 @@
-#!/usr/bin/env python3
+#!/usr/bin/env bash
 
-from sys import argv
-from os import cpu_count
+cpufreq_path=/sys/devices/system/cpu/cpu0/cpufreq
 
-cpufreq_path = '/sys/devices/system/cpu/cpu0/cpufreq/'
+usage() {
+    echo 'Governor changer'
+    echo
+    echo 'Options:'
+    echo '    -c             Check current active governor'
+    echo '    -l             List available governors'
+    echo '    -s [governor]  Set specified governor (root)'
+    echo 
 
-def current_governor():
-    with open(cpufreq_path + 'scaling_governor', 'r') as f:
-        current_governor = f.read().strip()
-        return current_governor
+    exit 0
+}
 
-def list_governors():
-    with open(cpufreq_path + 'scaling_available_governors', 'r') as f:
-        available_governors = f.read().strip().split(' ')
-        return available_governors
+current_governor() {
+    echo "Current governor: $(cat $cpufreq_path/scaling_governor)"
+}
 
-def set_governor(governor):
-    for cpu in range(0, cpu_count()):
-        cpufreq_path ='/sys/devices/system/cpu/cpu%d/cpufreq/' % cpu
+list_governors() {
+    governors=$(cat $cpufreq_path/scaling_available_governors | sed 's/\s/\n/g')
 
-        try:
-            with open(cpufreq_path + 'scaling_governor', 'w') as f:
-                f.write(governor)
-        except:
-            print('Unable to set governor. Try to run with root privileges.')
-            exit(1)
+    echo 'Available governors: '
+    for i in $governors; do
+        echo " - $i"
+    done
+}
 
-# =================================
+set_governor() {
+    if [[ $(id -u) -ne 0 ]]; then
+        echo 'Unable to set governor. Try to run with root privileges'
+        exit 1
+    fi
+    
+    cpu_count=$(cat /proc/cpuinfo | grep processor | wc -l) 
+    for (( i=0; i < $cpu_count; i++ )); do
+        cpufreq_path=/sys/devices/system/cpu/cpu$i/cpufreq
+        echo $1 > $cpufreq_path/scaling_governor
+    done
 
-def print_help():
-    print('Governor changer')
-    print()
-    print('Options:')
-    print('    -c            Check current active governor')
-    print('    -l            List available governors')
-    print('    -s [governor] Set specified governor (root)')
-    print()
+    exit 0
+}
 
-    exit()
+main() {
+    while [[ -n "$1" ]]; do
+        for opt in $@; do
+            case $opt in
+                -c)  current_governor  ;;
+                -l)  list_governors    ;;
+                -s)  set_governor $2   ;;
+                -h)  usage             ;;
+                 *)  usage             ;;
+            esac
+            shift
+        done
+    done
+   
+}
 
-if len(argv) < 2:
-    print_help()
-
-if argv[1] == '-c':
-    print('Current governor:', current_governor())
-
-    exit()
-
-if argv[1] == '-l':
-    available_governors = list_governors()
-    pretty_list = ''
-    for governor in available_governors:
-        pretty_list += '\n - ' + governor
-    print('Available governors:'+pretty_list)
-
-    exit()
-
-if argv[1] == '-s':
-    if len(argv) < 3:
-        print('Specifiy governor to apply')
-        print('Example: governor -s powersave')
-        exit()
-    governor = argv[2]
-    set_governor(governor)
-
-    exit()
-else:
-    print_help()
+main $@
